NDefines.NCountry.MIN_FOCUSES_FOR_CONTINUOUS = 2

NDefines.NCountry.DAYS_OF_WAR_BEFORE_SURRENDER = 4
NDefines.NGame.MESSAGE_TIMEOUT_DAYS = 14


NDefines.NAI.MINIMUM_EQUIPMENT_TO_ASK_LEND_LEASE = -1999999
NDefines.NDiplomacy.FRONT_IS_DANGEROUS = 0
NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_OPINION_PENALTY = 0

NDefines.NCountry.SURRENDER_LIMIT_REDUCTION_PER_COLLABORATION = 0
NDefines.NDiplomacy.TRUCE_PERIOD_AFTER_KICKING_FROM_FACTION = 0
NDefines.NDiplomacy.NUM_DAYS_TO_ENABLE_KICKING_NEW_MEMBERS_OF_FACTION = 0
NDefines.NDiplomacy.NUM_DAYS_TO_ENABLE_REINVITE_KICKED_NATIONS = 0
NDefines.NDiplomacy.VOLUNTEERS_PER_COUNTRY_ARMY = 1
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 0

NDefines.NDiplomacy.PEACE_SCORE_PER_PASS = 100.0
NDefines.NDiplomacy.GUARANTEE_COST = 1000


NDefines.NCountry.MAX_PROPAGANDA_WAR_SUPPORT_IMPACT = 0
NDefines.NCountry.MAX_PROPAGANDA_STABILITY_IMPACT = 0
NDefines.NOperatives.OPERATIVE_BASE_BOOST_IDEOLOGY = 0
NDefines.NOperatives.OPERATIVE_BASE_PROPAGANDA_POWER = 0

NDefines.NOperatives.AGENCY_CREATION_DAYS = 0
NDefines.NOperatives.AGENCY_CREATION_FACTORIES = 0
NDefines.NOperatives.AGENCY_UPGRADE_DAYS = 100
NDefines.NOperatives.BECOME_SPYMASTER_PP_COST = 0
NDefines.NOperatives.BECOME_SPYMASTER_MIN_UPGRADES = 0
NDefines.NOperatives.AGENCY_OPERATIVE_RECRUITMENT_TIME = 5


NDefines.NMilitary.UNIT_LEADER_MODIFIER_COOLDOWN_ON_GROUP_CHANGE = 0
NDefines.NMilitary.UNIT_LEADER_ASSIGN_TRAIT_COST = 0.00

NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 0
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 0
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 0


NDefines.NAir.AIR_WING_MAX_SIZE = 1600
NDefines.NAir.AIR_DEPLOYMENT_DAYS = 0

NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 48
NDefines.NProduction.MIN_POSSIBLE_TRAINING_MANPOWER = 10000000

NDefines.NProduction.MAX_MIL_FACTORIES_PER_LINE = 300
NDefines.NProduction.CONVOY_MAX_NAV_FACTORIES_PER_LINE = 100
NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 100
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 100

NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 0.0
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 0.0
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 0.0
NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST = 0.0

NDefines.NProduction.MIN_LICENSE_ACTIVE_DAYS = 1
NDefines.NProduction.LICENSE_EQUIPMENT_BASE_SPEED = 0
NDefines.NProduction.LICENSE_EQUIPMENT_TECH_SPEED_PER_YEAR = 0
NDefines.NProduction.LICENSE_EQUIPMENT_TECH_SPEED_MAX_YEARS = 0
NDefines.NProduction.LICENSE_EQUIPMENT_SPEED_NOT_FACTION = 0
NDefines.NProduction.LICENSE_EQUIPMENT_UPGRADE_XP_FACTOR = 1
NDefines.NProduction.LICENSE_EQUIPMENT_SPEED_NO_LICENSE = -1
